routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Models\Event;
use Illuminate\Support\Facades\Mail;

Route::get('/send-mail', function () {

    $event = Event::findOrFail(44);
    $event->notifyAttendees();
    return 'A message has been sent to Mailtrap!';

});


Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

/*  USER ROUTES  */
Route::resource('user', 'UserController');

/*  EVENT ROUTES  */
Route::get('event/search', 'Events\EventSearchController')->name('event.search');
Route::resource('event', 'Events\EventsController');


/*********************************/
/*  CONTACT ROUTES              */
/*********************************/
Route::get('contacts/search', 'Users\UserRelationshipSearchController')->name('contacts.search');
Route::resource('contacts', 'UserRelationshipsController')->only(['index', 'store', 'destroy']);

/*********************************/
/*  RELATIONSHIP REQUEST ROUTES  */
/*********************************/
Route::resource('relationship-requests', 'UserRelationshipRequestsController');
Route::put('relationship-requests/{relationship}/accept', 'Relationships\AcceptRelationshipRequestController')->name('relationship-requests.accept');


/*********************************/
/*  ATTENDEE REQUEST ROUTES     */
/*********************************/
Route::get('attendee-requests', 'Attendees\FetchAttendeeRequestsController');
Route::delete('attendee-request/{attendee}/decline', 'Attendees\DeclineAttendeeRequestController')->name('attendee-requests.decline');
Route::put('attendee-requests/{attendee}/accept', 'Attendees\AcceptAttendeeRequestController')->name('attendee-requests.accept');

/*********************************/
/*  ATTENDEE ROUTES              */
/*********************************/
Route::post('/attendee/search', 'Events\SearchNewAttendeesController');
Route::post('/attendee/storeMany', 'Attendees\StoreManyAttendeeController')->name('attendee.storeMany');
Route::resource('attendee', 'Attendees\AttendeeController')->only(['store', 'destroy']);

resources/views/attendee-requests/partials/_indexHeader.blade.php
<div class="flex flex-row border-b-2 border-warm-grey-500  mb-2 p-2">
    <div class="text-warm-grey-0 text-xl md:text-2xl">
        <i class="fas fa-archive pr-2"></i>Event Requests
    </div>
</div>

resources/views/attendee-requests/partials/_indexResults.blade.php
<div class="list-group">
    @forelse($requests as $request)
        <div class="list-group-item px-2">
            <div class="flex flex-col md:flex-row">

                <div class="w-full flex self-center p-2 rounded hover:bg-grey-light md:shadow-md md:w-3/4">
                    <a href="{{ route('event.show', $request->event ) }}"
                       class="text-decoration-none flex flex-row flex-wrap">
                        <div class="text-sm text-grey-darkest px-2 md:text-lg md:flex-shrink">
                            <i class="far fa-eye"></i>
                        </div>
                        <div class="text-sm font-bold align-self-center text-grey-darkest md:w-5/6">
                            {{ $request->event->name }}
                        </div>
                        <div class="hidden text-grey-darker text-sm md:block md:w-full">
                            {{ $request->event->description }}
                        </div>
                    </a>
                </div>

                <div class="w-full flex md:w-1/4">
                    <div class="mx-2 w-1/2 flex self-center justify-center">
                        <form action="{{ route('attendee-requests.decline', $request->id ) }}" method="POST">
                            @csrf
                            @method('DELETE')
                            <button class="btn bg-red hover:bg-red-dark text-white text-sm shadow md:text-lg">
                                <i class="far fa-2x fa-calendar-times"></i>
                            </button>
                        </form>
                    </div>
                    <div class="w-1/2 flex self-center justify-center">
                        <form action="{{ route('attendee-requests.accept', ['attendee' => $request]) }}"
                              method="POST">
                            @csrf
                            @method('PUT')
                            <button class="btn text-white bg-yellow-dark hover:bg-yellow text-sm shadow md:text-lg">
                                <i class="far fa-2x fa-calendar-check"></i>
                            </button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    @empty
        <div class="p-2">
            No Contact Requests
        </div>
    @endforelse
</div>