routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Models\Event;
use Illuminate\Support\Facades\Mail;

Route::get('/send-mail', function () {

    $event = Event::findOrFail(44);
    $event->notifyAttendees();
    return 'A message has been sent to Mailtrap!';

});


Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

/*  USER ROUTES  */
Route::resource('user', 'UserController');

/*  EVENT ROUTES  */
Route::get('event/search', 'Events\EventSearchController')->name('event.search');
Route::resource('event', 'Events\EventsController');


/*********************************/
/*  CONTACT ROUTES              */
/*********************************/
Route::get('contacts/search', 'Users\UserRelationshipSearchController')->name('contacts.search');
Route::resource('contacts', 'UserRelationshipsController')->only(['index', 'store', 'destroy']);

/*********************************/
/*  RELATIONSHIP REQUEST ROUTES  */
/*********************************/
Route::resource('relationship-requests', 'UserRelationshipRequestsController');
Route::put('relationship-requests/{relationship}/accept', 'Relationships\AcceptRelationshipRequestController')->name('relationship-requests.accept');


/*********************************/
/*  ATTENDEE REQUEST ROUTES     */
/*********************************/
Route::get('attendee-requests', 'Attendees\FetchAttendeeRequestsController');
Route::delete('attendee-request/{attendee}/decline', 'Attendees\DeclineAttendeeRequestController')->name('attendee-requests.decline');
Route::put('attendee-requests/{attendee}/accept', 'Attendees\AcceptAttendeeRequestController')->name('attendee-requests.accept');

/*********************************/
/*  ATTENDEE ROUTES              */
/*********************************/
Route::post('/attendee/search', 'Events\SearchNewAttendeesController');
Route::post('/attendee/storeMany', 'Attendees\StoreManyAttendeeController')->name('attendee.storeMany');
Route::resource('attendee', 'Attendees\AttendeeController')->only(['store', 'destroy']);

app/Models/Event/Event.php
<?php

namespace App\Models;

use App\Mail\MailEventReminder;
use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\Mail;

/**
 * @property mixed eventAttendees
 * @property mixed repeated
 * @property mixed rsvp_by
 * @property mixed description
 * @property mixed address
 * @property mixed name
 */
class Event extends Model
{
    use SoftDeletes;

    protected $fillable = [
        'name',
        'address',
        'description',
        'rsvp_by',
        'starts_at',
        'ends_at',
        'repeated',
        'repeated_type_id',
    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function attendees()
    {
        return $this->hasMany(Attendee::class);
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasOne
     */
    public function repeatedType()
    {
        return $this->hasOne(RepeatedType::class, 'repeated_type_id');
    }

    /**
     * @param $val
     * (Sets the repeated value )
     */
    public function setRepeatedAttribute($val)
    {
        $this->attributes['repeated'] = (bool)$val;
    }

    /**
     * @return int
     */
    public function getRepeatedTypeIdAttribute()
    {
        return $this->attributes['repeated_type_id'] === null ? 0 : $this->attributes['repeated_type_id'];
    }

    /**
     * @return string
     * (Returns a date that is in readable format.)
     */
    public function getStartsAtDiffAttribute()
    {
        return Carbon::parse($this->starts_at)->diffForHumans();
    }

    /**
     *  Retrieves all Attendees(Users) that are attending the specified Event
     */
    public function getEventAttendeesAttribute()
    {
        return Attendee::where('event_id', '=', $this->id)->get();
    }

    /**
     * @param $query
     * @return mixed (Finds all Events the logged in user is attending)
     */
    public function scopeEventsCurrentlyIn($query)
    {
        return $query->whereIn('id', auth()->user()->attendingEvents->pluck('event_id'));
    }

    /**
     * @param $query
     * @return mixed (Finds all Events the logged in user is not attending)
     */
    public function scopeEventsCurrentlyNotIn($query)
    {
        return $query->whereNotIn('id', auth()->user()->attendingEvents->pluck('event_id'));
    }

    /**
     * @param $query
     * @param $days
     * @return mixed
     */
    public function scopeWithinDays($query, $days)
    {
        return $query->whereBetween('starts_at', [now(), now()->addDays($days)]);
    }

    /**
     * @param $user
     */
    private function sendMessage($user)
    {
        $this->info("Sending Message to {$user->name}");

        if (config('app.env') === 'production') {
            Mail::to($user->email)->send(new MailEventReminder($this, $user->name));
        }
    }

    /**
     * Send SMS notification to attendees of the current event
     */
    public function notifyAttendees()
    {
        $this->attendees->each(function ($attendee) {
            $this->sendMessage($attendee->user);
        });
    }

}

app/Models/Event/RepeatedType.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class RepeatedType extends Model
{
    protected $fillable = [];

    public static function yearly()
    {
        return RepeatedType::where('name', '=', 'Yearly')->get()->id;
    }

    public static function monthly()
    {
        return RepeatedType::where('name', '=', 'Yearly')->get()->id;
    }

    public static function weekly()
    {
        return RepeatedType::where('name', '=', 'Yearly')->get()->id;
    }

    public static function daily()
    {
        return RepeatedType::where('name', '=', 'Yearly')->get()->id;
    }



}

app/Http/Controllers/Events/EventSearchController.php
<?php

namespace App\Http\Controllers\Events;

use App\Models\Event;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class EventSearchController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Handle the incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function __invoke(Request $request)
    {
        $events = Event::eventsCurrentlyNotIn()
            ->where('events.name', 'like', request('search') . '%')
            ->orderBy('events.starts_at')
            ->paginate(10);

        return view('event.search', [
            'events' => $events,
            'search' => $request->get('search'),
        ]);
    }
}

app/Http/Controllers/Events/EventsController.php
<?php

namespace App\Http\Controllers\Events;

use App\Http\Controllers\Controller;
use App\Http\Requests\EventRequest;
use App\Models\Attendee;
use App\Models\AttendeeStatus;
use App\Models\AttendeeType;
use App\Models\Event;
use App\Models\RepeatedType;
use Exception;
use Illuminate\Http\Response;

class EventsController extends Controller
{

    /**
     * EventsController constructor.
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        $events = Event::eventsCurrentlyIn()->orderBy('events.starts_at')->paginate(10);

        return view('event.index', [
            'events' => $events
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        $this->authorize('events.create');
        return view('event.create', [
            'repeatedTypes' => RepeatedType::all(),
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param EventRequest $request
     * @return Response
     */
    public function store(EventRequest $request)
    {
        $this->authorize('events.create');
        $event = Event::create($request->all());
        Attendee::addAttendee(auth()->user()->id, $event->id, AttendeeType::HOST, AttendeeStatus::ATTENDING);
        return redirect()->route('event.index')->with('message', 'Event Created!');
    }

    /**
     * Display the specified resource.
     *
     * @param Event $event
     * @return Response
     */
    public function show(Event $event)
    {
        $this->authorize('events.view', $event);
        return view('event.show', [
            'event' => $event,
            'attendees' => $event->eventAttendees,
            'repeatedTypes' => RepeatedType::all(),
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Event $event
     * @return Response
     */
    public function edit(Event $event)
    {
        $this->authorize('events.update', $event);
        return view('event.edit', [
            'event' => $event,
            'attendees' => $event->eventAttendees,
            'repeatedTypes' => RepeatedType::all(),
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param EventRequest $request
     * @param Event $event
     * @return Response
     */
    public function update(EventRequest $request, Event $event)
    {
        $this->authorize('events.update', $event);
        $event->update($request->all());
        return back()->with('message', 'Event Updated!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Event $event
     * @return Response
     * @throws Exception
     */
    public function destroy(Event $event)
    {
        $this->authorize('events.delete', $event);
        $event->delete();
        return redirect()->route('event.index')->with('message', 'Event Removed!');
    }
}

app/Http/Controllers/Events/SearchNewAttendeesController.php
<?php

namespace App\Http\Controllers\Events;


use App\Http\Requests\Attendee\AttendeeSearchRequest;
use App\Models\Event;
use App\Models\User;
use App\Http\Controllers\Controller;

class SearchNewAttendeesController extends Controller
{

    /**
     * InviteAttendeesController constructor.
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Handle the incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function __invoke(AttendeeSearchRequest $request)
    {
        $event = Event::findOrFail($request->get('eventId'));
        $attendees = $event->attendees()->pluck('user_id');

        $users = User::whereNotIn('id', $attendees->toArray())
            ->where('name', 'like', $request->get('search') . '%')
            ->orderBy('name')
            ->get(['id','name']);

        return response()->json($users);
    }
}

resources/views/event/partials/_indexHeader.blade.php
<div class="ml-5 mb-3">
	<div class="flex justify-between">
		<div class=" self-center text-warm-grey-0 text-xl md:text-2xl" ><i class="fas fa-calendar-day pr-2"></i>My Events</div>
		<div class="text-xs md:text-base">
			<inv-button link="{{ route('event.create') }}" color="rounded outline-none bg-yellow-dark text-white hover:bg-yellow focus:shadow-outline  p-2 m-0">
				<i class="fas fa-plus p-1"></i>
				<div class="md:inline-block hidden">
					Create Event
				</div>
			</inv-button>
		</div>

	</div>
</div>

resources/views/event/partials/_results.blade.php
@forelse($events as $event)
    <div class="border-t-2 border-warm-grey-800 ml-5"></div>
    <div class="flex  w-full">
        <div class="timeline-ball md:mt-5 mt-8"></div>
        <div class="py-3 pl-5 w-full flex-col">
            <div class="flex justify-between mb-3">

                <div class="flex flex-col">
                    <h4 class="text-sm md:text-base md:font-bold lg:text-lg font-semibold text-warm-grey-200">{{ $event->name }}</h4>
                    <div class="text-sm md:text-base text-warm-grey-200">
                        {{ $event->starts_at_diff }}
                    </div>
                </div>
                <div>
                    @if(auth()->user()->isEventHost($event->id))
                        <inv-button link="{{ route('event.edit', ['id' => $event->id])}}"
                                    color="bg-yellow-lightest leading-none text-red-darkest border-2 border-red-darkest hover:bg-yellow-lighter font-semibold text-sm p-2 m-0">
                            <i class="far fa-edit p-1"></i>
                            <div class="md:inline-block hidden">
                                Edit
                            </div>
                        </inv-button>
                    @endif
                </div>
            </div>

            <div class="hidden md:flex md:w-5/6 text-warm-grey-200 md:block">
                {{ $event->description }}
            </div>


            @if(!auth()->user()->isEventHost($event->id))
                <div class="flex my-2 text-xs md:text-base">
                    <inv-button link="{{ route('event.show', ['id' => $event->id]) }}"
                                color="bg-yellow-lighter text-red-darkest shadow hover:bg-yellow-light font-semibold">
                        <i class="fas fa-search-location"></i> Check it out
                    </inv-button>
                </div>
            @endif
        </div>
    </div>
@empty
    No Events to Show.
@endforelse

resources/views/event/partials/_searchHeader.blade.php
<div class="ml-5 mb-3">
    <div class="flex flex-col">
        <div class="w-full flex">
            <div class="w-1/2 self-center text-warm-grey-0 text-xl md:text-2xl">
                <i class="fas fa-calendar-day pr-2"></i>Events
            </div>
            <div class="w-1/2 flex justify-end text-xs md:text-base">
                <inv-button link="{{ route('event.create') }}"
                            color="rounded outline-none bg-yellow-dark text-white hover:bg-yellow p-2 m-0">
                    <i class="fas fa-plus p-1"></i>
                    <div class="md:inline-block hidden">Create Event</div>
                </inv-button>
            </div>
        </div>

        <form method="GET" action="{{ route('event.search') }}" class="w-full">
            @csrf
            <inv-input-search url-path="{{ route('event.search') }}" value="{{ isset($search) ? $search : '' }}"></inv-input-search>
        </form>


    </div>
</div>