routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Models\Event;
use Illuminate\Support\Facades\Mail;

Route::get('/send-mail', function () {

    $event = Event::findOrFail(44);
    $event->notifyAttendees();
    return 'A message has been sent to Mailtrap!';

});


Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

/*  USER ROUTES  */
Route::resource('user', 'UserController');

/*  EVENT ROUTES  */
Route::get('event/search', 'Events\EventSearchController')->name('event.search');
Route::resource('event', 'Events\EventsController');


/*********************************/
/*  CONTACT ROUTES              */
/*********************************/
Route::get('contacts/search', 'Users\UserRelationshipSearchController')->name('contacts.search');
Route::resource('contacts', 'UserRelationshipsController')->only(['index', 'store', 'destroy']);

/*********************************/
/*  RELATIONSHIP REQUEST ROUTES  */
/*********************************/
Route::resource('relationship-requests', 'UserRelationshipRequestsController');
Route::put('relationship-requests/{relationship}/accept', 'Relationships\AcceptRelationshipRequestController')->name('relationship-requests.accept');


/*********************************/
/*  ATTENDEE REQUEST ROUTES     */
/*********************************/
Route::get('attendee-requests', 'Attendees\FetchAttendeeRequestsController');
Route::delete('attendee-request/{attendee}/decline', 'Attendees\DeclineAttendeeRequestController')->name('attendee-requests.decline');
Route::put('attendee-requests/{attendee}/accept', 'Attendees\AcceptAttendeeRequestController')->name('attendee-requests.accept');

/*********************************/
/*  ATTENDEE ROUTES              */
/*********************************/
Route::post('/attendee/search', 'Events\SearchNewAttendeesController');
Route::post('/attendee/storeMany', 'Attendees\StoreManyAttendeeController')->name('attendee.storeMany');
Route::resource('attendee', 'Attendees\AttendeeController')->only(['store', 'destroy']);

resources/views/relationship-requests/partials/_indexHeader.blade.php
<div class="flex w-full border-warm-grey-500 border-b-2 mb-2 p-2">
        <div class="self-center text-warm-grey-0 text-lg md:text-xl lg:text-2xl">
            <i class="fas fa-archive pr-2"></i>Requests
        </div>
</div>

resources/views/relationship-requests/partials/_indexResults.blade.php
<div class="list-group">
    @forelse($requests as $request)
        <div class="list-group-item">

            <div class="flex flex-wrap w-full rounded">

                    <div class="w-full self-center md:w-2/4">
                        <div class="font-semibold text-warm-grey-0 text-sm md:text-lg lg:text-xl">
                            {{ $request->user->name }}
                        </div>
                        <div class="text-warm-grey-200 text-sm md:text-base">
                            {{ $request->user->email }}
                        </div>
                    </div>

                    <inv-relationship-status class="w-full md:w-1/4"
                        relationship-type="{{ $request->type->name }}"
                        relationship-status="{{ $request->status->name }}"></inv-relationship-status>

                    <div class="w-full flex self-center justify-around md:w-1/4">
                        <div class="w-1/2 flex self-center justify-center">
                            <form action="{{ route('contacts.destroy', $request->user_id ) }}" method="POST">
                                @csrf
                                @method('DELETE')
                                <button class="btn bg-red-dark hover:bg-red text-white text-sm md:text-2xl">
                                    <i class="fas fa-ban"></i>
                                </button>
                            </form>
                        </div>
                        <div class="w-1/2 flex self-center justify-center">
                            <form action="{{ route('relationship-requests.accept', ['relationship' => $request]) }}"
                                  method="POST">
                                @csrf
                                @method('PUT')

                                <button class="btn bg-yellow-dark text-white hover:bg-yellow text-sm md:text-2xl">
                                    <i class="fas fa-check"></i>
                                </button>
                            </form>
                        </div>
                    </div>
            </div>

        </div>
    @empty
        <i class="fas fa-sad-cry"></i> No Contact Requests
    @endforelse
</div>