routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Models\Event;
use Illuminate\Support\Facades\Mail;

Route::get('/send-mail', function () {

    $event = Event::findOrFail(44);
    $event->notifyAttendees();
    return 'A message has been sent to Mailtrap!';

});


Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

/*  USER ROUTES  */
Route::resource('user', 'UserController');

/*  EVENT ROUTES  */
Route::get('event/search', 'Events\EventSearchController')->name('event.search');
Route::resource('event', 'Events\EventsController');


/*********************************/
/*  CONTACT ROUTES              */
/*********************************/
Route::get('contacts/search', 'Users\UserRelationshipSearchController')->name('contacts.search');
Route::resource('contacts', 'UserRelationshipsController')->only(['index', 'store', 'destroy']);

/*********************************/
/*  RELATIONSHIP REQUEST ROUTES  */
/*********************************/
Route::resource('relationship-requests', 'UserRelationshipRequestsController');
Route::put('relationship-requests/{relationship}/accept', 'Relationships\AcceptRelationshipRequestController')->name('relationship-requests.accept');


/*********************************/
/*  ATTENDEE REQUEST ROUTES     */
/*********************************/
Route::get('attendee-requests', 'Attendees\FetchAttendeeRequestsController');
Route::delete('attendee-request/{attendee}/decline', 'Attendees\DeclineAttendeeRequestController')->name('attendee-requests.decline');
Route::put('attendee-requests/{attendee}/accept', 'Attendees\AcceptAttendeeRequestController')->name('attendee-requests.accept');

/*********************************/
/*  ATTENDEE ROUTES              */
/*********************************/
Route::post('/attendee/search', 'Events\SearchNewAttendeesController');
Route::post('/attendee/storeMany', 'Attendees\StoreManyAttendeeController')->name('attendee.storeMany');
Route::resource('attendee', 'Attendees\AttendeeController')->only(['store', 'destroy']);

app/Models/Event/Event.php
<?php

namespace App\Models;

use App\Mail\MailEventReminder;
use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\Mail;

/**
 * @property mixed eventAttendees
 * @property mixed repeated
 * @property mixed rsvp_by
 * @property mixed description
 * @property mixed address
 * @property mixed name
 */
class Event extends Model
{
    use SoftDeletes;

    protected $fillable = [
        'name',
        'address',
        'description',
        'rsvp_by',
        'starts_at',
        'ends_at',
        'repeated',
        'repeated_type_id',
    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function attendees()
    {
        return $this->hasMany(Attendee::class);
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasOne
     */
    public function repeatedType()
    {
        return $this->hasOne(RepeatedType::class, 'repeated_type_id');
    }

    /**
     * @param $val
     * (Sets the repeated value )
     */
    public function setRepeatedAttribute($val)
    {
        $this->attributes['repeated'] = (bool)$val;
    }

    /**
     * @return int
     */
    public function getRepeatedTypeIdAttribute()
    {
        return $this->attributes['repeated_type_id'] === null ? 0 : $this->attributes['repeated_type_id'];
    }

    /**
     * @return string
     * (Returns a date that is in readable format.)
     */
    public function getStartsAtDiffAttribute()
    {
        return Carbon::parse($this->starts_at)->diffForHumans();
    }

    /**
     *  Retrieves all Attendees(Users) that are attending the specified Event
     */
    public function getEventAttendeesAttribute()
    {
        return Attendee::where('event_id', '=', $this->id)->get();
    }

    /**
     * @param $query
     * @return mixed (Finds all Events the logged in user is attending)
     */
    public function scopeEventsCurrentlyIn($query)
    {
        return $query->whereIn('id', auth()->user()->attendingEvents->pluck('event_id'));
    }

    /**
     * @param $query
     * @return mixed (Finds all Events the logged in user is not attending)
     */
    public function scopeEventsCurrentlyNotIn($query)
    {
        return $query->whereNotIn('id', auth()->user()->attendingEvents->pluck('event_id'));
    }

    /**
     * @param $query
     * @param $days
     * @return mixed
     */
    public function scopeWithinDays($query, $days)
    {
        return $query->whereBetween('starts_at', [now(), now()->addDays($days)]);
    }

    /**
     * @param $user
     */
    private function sendMessage($user)
    {
        $this->info("Sending Message to {$user->name}");

        if (config('app.env') === 'production') {
            Mail::to($user->email)->send(new MailEventReminder($this, $user->name));
        }
    }

    /**
     * Send SMS notification to attendees of the current event
     */
    public function notifyAttendees()
    {
        $this->attendees->each(function ($attendee) {
            $this->sendMessage($attendee->user);
        });
    }

}

app/Models/Event/RepeatedType.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class RepeatedType extends Model
{
    protected $fillable = [];

    public static function yearly()
    {
        return RepeatedType::where('name', '=', 'Yearly')->get()->id;
    }

    public static function monthly()
    {
        return RepeatedType::where('name', '=', 'Yearly')->get()->id;
    }

    public static function weekly()
    {
        return RepeatedType::where('name', '=', 'Yearly')->get()->id;
    }

    public static function daily()
    {
        return RepeatedType::where('name', '=', 'Yearly')->get()->id;
    }



}

app/Http/Controllers/Events/EventSearchController.php
<?php

namespace App\Http\Controllers\Events;

use App\Models\Event;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class EventSearchController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Handle the incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function __invoke(Request $request)
    {
        $events = Event::eventsCurrentlyNotIn()
            ->where('events.name', 'like', request('search') . '%')
            ->orderBy('events.starts_at')
            ->paginate(10);

        return view('event.search', [
            'events' => $events,
            'search' => $request->get('search'),
        ]);
    }
}

app/Http/Controllers/Events/EventsController.php
<?php

namespace App\Http\Controllers\Events;

use App\Http\Controllers\Controller;
use App\Http\Requests\EventRequest;
use App\Models\Attendee;
use App\Models\AttendeeStatus;
use App\Models\AttendeeType;
use App\Models\Event;
use App\Models\RepeatedType;
use Exception;
use Illuminate\Http\Response;

class EventsController extends Controller
{

    /**
     * EventsController constructor.
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        $events = Event::eventsCurrentlyIn()->orderBy('events.starts_at')->paginate(10);

        return view('event.index', [
            'events' => $events
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        $this->authorize('events.create');
        return view('event.create', [
            'repeatedTypes' => RepeatedType::all(),
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param EventRequest $request
     * @return Response
     */
    public function store(EventRequest $request)
    {
        $this->authorize('events.create');
        $event = Event::create($request->all());
        Attendee::addAttendee(auth()->user()->id, $event->id, AttendeeType::HOST, AttendeeStatus::ATTENDING);
        return redirect()->route('event.index')->with('message', 'Event Created!');
    }

    /**
     * Display the specified resource.
     *
     * @param Event $event
     * @return Response
     */
    public function show(Event $event)
    {
        $this->authorize('events.view', $event);
        return view('event.show', [
            'event' => $event,
            'attendees' => $event->eventAttendees,
            'repeatedTypes' => RepeatedType::all(),
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Event $event
     * @return Response
     */
    public function edit(Event $event)
    {
        $this->authorize('events.update', $event);
        return view('event.edit', [
            'event' => $event,
            'attendees' => $event->eventAttendees,
            'repeatedTypes' => RepeatedType::all(),
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param EventRequest $request
     * @param Event $event
     * @return Response
     */
    public function update(EventRequest $request, Event $event)
    {
        $this->authorize('events.update', $event);
        $event->update($request->all());
        return back()->with('message', 'Event Updated!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Event $event
     * @return Response
     * @throws Exception
     */
    public function destroy(Event $event)
    {
        $this->authorize('events.delete', $event);
        $event->delete();
        return redirect()->route('event.index')->with('message', 'Event Removed!');
    }
}

app/Http/Controllers/Events/SearchNewAttendeesController.php
<?php

namespace App\Http\Controllers\Events;


use App\Http\Requests\Attendee\AttendeeSearchRequest;
use App\Models\Event;
use App\Models\User;
use App\Http\Controllers\Controller;

class SearchNewAttendeesController extends Controller
{

    /**
     * InviteAttendeesController constructor.
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Handle the incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function __invoke(AttendeeSearchRequest $request)
    {
        $event = Event::findOrFail($request->get('eventId'));
        $attendees = $event->attendees()->pluck('user_id');

        $users = User::whereNotIn('id', $attendees->toArray())
            ->where('name', 'like', $request->get('search') . '%')
            ->orderBy('name')
            ->get(['id','name']);

        return response()->json($users);
    }
}

resources/views/event/create.blade.php
@extends('layouts.app')


@section('content')

	<div class="container">
		<div class="flex w-full justify-center">
			<div class="card shadow w-full sm:w-3/4 lg:w-1/2">
				<div class="card-body">
					<div class="self-center text-warm-grey-0 text-sm border-warm-grey-500 border-b-2 mb-2 p-2 md:text-lg lg:text-2xl ">
						<i class="fas fa-calendar-plus"></i> Create Event
					</div>
					<form action="{{ route('event.store') }}" method="POST">
						@csrf

						<inv-form-group label="Name" name="name"
						                error-text="{{ $errors->first('name') }}"
										value="{{ old('name')  }}"
						></inv-form-group>

						<inv-form-group label="Address" name="address"
						                error-text="{{ $errors->first('address') }}"
										value="{{ old('address') }}"
						></inv-form-group>

						<inv-form-group label="Description" name="description" type="textarea"
						                error-text="{{ $errors->first('description') }}"
						                value="{{ old('description') }}"
						></inv-form-group>

						<inv-form-group label="RSVP" name="rsvp_by" type="dateTime"
						                required
						                value="{{ old('rsvp_by') ? Carbon::parse(old('rsvp_by'))->format('c') : ''  }}"
						                error-text="{{ $errors->first('rsvp_by') }}"
						></inv-form-group>

						<inv-form-group label="Starts At" name="starts_at" type="dateTime"
						                required
						                value="{{ old('starts_at') ? Carbon::parse(old('starts_at'))->format('c') : '' }}"
						                error-text="{{ $errors->first('starts_at') }}"
						></inv-form-group>

						<inv-form-group label="Ends At" name="ends_at" type="dateTime"
						                required
						                value="{{ old('ends_at') ? Carbon::parse(old('ends_at'))->format('c') : '' }}"
						                error-text="{{ $errors->first('ends_at') }}"
						></inv-form-group>

						<div class="form-group">
							<inv-event-repeated :types="{{ $repeatedTypes }}"></inv-event-repeated>
						</div>

						<div class="flex justify-end">
							<a href="{{ route('event.index') }}"
							   class="btn bg-yellow-lighter hover:bg-yellow-light text-red-darkest font-bold shadow text-sm md:text-base lg:text-lg mr-2">
								Cancel
							</a>

							<button class="btn bg-yellow-dark hover:bg-yellow text-white font-bold text-sm md:text-base lg:text-lg shadow">
								<i class="fas fa-save"></i> Save
							</button>
						</div>


					</form>
				</div>
			</div>
		</div>
	</div>



@endsection

resources/views/event/edit.blade.php
@extends('layouts.app')


@section('content')

	<div class="container">
		<div class="flex w-full justify-center">
			<div class="card shadow w-full sm:w-3/4 lg:w-1/2">
				<div class="card-body">
					<div class="flex self-end justify-between border-warm-grey-500 border-b-2 mb-2 p-2">
						<div class="self-center text-warm-grey-0 text-sm md:text-lg lg:text-xl ">
							<i class="fas fa-calendar-plus"></i> {{ $event->name }}
						</div>
						<form action="{{ route('event.destroy', ['id' => $event->id]) }}" method="POST">
							@csrf
							@method('DELETE')
							<button class="btn text-sm text-white font-semibold bg-red hover:bg-red-dark rounded md:text-base lg:text-lg">
								<i class="fas fa-dumpster-fire"></i>
                                <div class="hidden md:inline-block">
                                    Delete
                                </div>
							</button>
						</form>
					</div>
					<form action="{{ route('event.update', $event ) }}" method="POST">
						@csrf
						@method('PUT')

						<inv-form-group label="Name" name="name" value="{{ old('name', $event->name) }}"
						                error-text="{{ $errors->first('name') }}"></inv-form-group>

						<inv-form-group label="Address" name="address"
						                value="{{ old('address', $event->address) }}"
						                error-text="{{ $errors->first('address') }}"></inv-form-group>

						<inv-form-group label="Description" name="description"
						                type="textarea"
						                value="{{  old('description', $event->description) }}"
						                error-text="{{ $errors->first('description') }}">
						</inv-form-group>

						<inv-form-group label="RSVP" name="rsvp_by" type="dateTime"
						                value="{{ old('rsvp_by', Carbon::parse($event->rsvp_by)->format('c')) }}"
						                error-text="{{ $errors->first('rsvp-by') }}"
						></inv-form-group>

						<inv-form-group label="Starts At" name="starts_at" type="dateTime"
						                value="{{ old('starts_at', Carbon::parse($event->starts_at)->format('c')) }}"
						                error-text="{{$errors->first('starts_at')}}"
						></inv-form-group>

						<inv-form-group label="Ends At" name="ends_at" type="dateTime"
						                value="{{ old('ends_at', Carbon::parse($event->ends_at)->format('c')) }}"
						                error-text="{{$errors->first('ends_at')}}"
						></inv-form-group>

						<div class="form-group">
							<inv-event-repeated :value="{{ $event->repeated }}"
							                    :current-type="{{ $event->repeated_type_id  }}"
							                    :types="{{ $repeatedTypes }}"></inv-event-repeated>
						</div>

						<div class="flex justify-end">
							<a href="{{ route('event.index') }}"
							   class="btn bg-warm-grey-700 hover:bg-warm-grey-500 font-semibold text-warm-grey-0 shadow-md text-sm md:text-base lg:text-lg mr-2">
								Cancel
							</a>

							<button class="btn bg-yellow-dark hover:bg-yellow text-white font-semibold shadow-md text-sm md:text-base lg:text-lg">
								Update
							</button>
						</div>
					</form>


					<div class="flex flex-row justify-between mt-10 mb-2 border-grey border-b-2">
						<div class="self-end text-sm md:text-lg lg:text-2xl font-bold">
							<i class="fas fa-user-friends"></i>Attendees
						</div>

						<div class="pb-1">
							<inv-attendee-modal :event-id="{{ $event->id }}"
							                    :is-host="{{auth()->user()->isEventHost($event->id) ? 'true' : 'false'}}"></inv-attendee-modal>
						</div>
					</div>


					<list-group-scrollable>
						@foreach($attendees as $attendee)
							<div class="list-group-item border-0">
								<div class="flex flex-wrap">
									<div class="w-3/4">
										<div class="text-sm font-bold text-grey-darkest md:text-base">
											{{ $attendee->user->name }}
										</div>
										<div class="text-grey-dark text-xs md:text-sm">
											{{ $attendee->user->email }}
										</div>
									</div>
									<div class="w-1/4 flex justify-end">
										@if(auth()->user()->isEventHost($event->id) && auth()->user()->id !== $attendee->user_id)
											<form action="{{ route('attendee.destroy',  $attendee ) }}"
											      method="POST">
												@csrf
												@method('DELETE')
												<button class="btn bg-red hover:bg-red-dark text-white font-bold text-xs md:text-base lg:text-lg shadow my-1">
													<i class="fa fa-user-times"></i>
												</button>
											</form>
										@endif
									</div>
									<div class="w-full">
										<inv-attendee-status attendee-type="{{ $attendee->attendeeType->name }}"
										                     attendee-status="{{ $attendee->attendeeStatus->name }}"></inv-attendee-status>
									</div>
								</div>
								<hr class="p-0 mb-0">
							</div>

						@endforeach
					</list-group-scrollable>
				</div>
			</div>
		</div>
	</div>

@endsection

resources/views/event/index.blade.php
@extends('layouts.app')


@section('content')

    <div class="container">
        <div class="col-12">
            <div class="row">
                <div class="col">
                    <div class="card shadow-md text-grey-darkest">
                        <div class="card-body">
                            <div class="timeline-border-gradient">
                                @include('event.partials._indexHeader')
                                @include('event.partials._results')
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="container flex justify-center my-3">
                    {{ $events->links() }}
                </div>
            </div>
        </div>
    </div>



@endsection

resources/views/event/search.blade.php
@extends('layouts.app')


@section('content')

	<div class="container">
		<div class="col-12">
			<div class="row">
				<div class="col">
					<div class="card text-grey-darkest shadow-md">
						<div class="card-body">
							<div class="timeline-border-gradient">
								@include('event.partials._searchHeader')
								@include('event.partials._results')
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="row">
				<div class="container flex justify-center my-3">
					{{ $events->links() }}
				</div>
			</div>
		</div>
	</div>



@endsection

resources/views/event/show.blade.php
@extends('layouts.app')


@section('content')

    <div class="container">
        <div class="flex w-full justify-center">
            <div class="card shadow w-full sm:w-3/4 lg:w-1/2">
                <div class="card-body">
                    <div class="flex justify-between border-b-2 border-warm-grey-700 mb-2 p-2">
                        <div class="flex-grow self-center text-xl lg:w-3/4 lg:text-xl ">
                            <i class="fas fa-calendar-plus"></i> {{ $event->name }}
                        </div>
                        <div class="self-center flex justify-end lg:w-1/4">

                            @if(!auth()->user()->isAttending($event->id ))
                                <form
                                    action="{{ route('attendee.store', ['userInvites' => [auth()->user()->id], 'eventId' => $event->id ]) }}"
                                    method="POST">
                                    @method('POST')
                                    @csrf
                                    <button
                                        class="btn bg-yellow-dark hover:bg-yellow text-white font-semibold shadow text-sm md:text-base lg:text-lg ">
                                        <i class="fas fa-calendar-plus md:mr-2"></i>
                                        <div class="hidden md:inline-block">
                                            Attend
                                        </div>
                                    </button>
                                </form>
                            @else
                                <form
                                    action="{{ route('attendee.destroy', auth()->user()->getUserAttendee($event->id) ) }}"
                                    method="POST">
                                    @method('DELETE')
                                    @csrf
                                    <button
                                        class="btn text-sm md:text-base bg-red hover:bg-red-dark font-semibold text-white lg:text-lg">
                                        <i class="fas fa-door-open md:mr-2"></i>
                                        <div class="hidden md:inline-block">
                                            Leave
                                        </div>
                                    </button>
                                </form>
                            @endif
                        </div>
                    </div>
                    <inv-form-group label="Name" name="name" value="{{ $event->name }}"
                                    is-disabled></inv-form-group>

                    <inv-form-group label="Address" name="address"
                                    value="{{ $event->address }}" is-disabled></inv-form-group>

                    <inv-form-group label="Description" name="description"
                                    type="textarea"
                                    value="{{  $event->description }}" is-disabled>
                    </inv-form-group>

                    <inv-form-group label="RSVP"
                                    value="{{ Carbon::parse($event->rsvp_by)->toDayDateTimeString() }}"
                                    is-disabled></inv-form-group>

                    <inv-form-group label="Starts At"
                                    value="{{ Carbon::parse($event->starts_at)->toDayDateTimeString() }}"
                                    is-disabled></inv-form-group>

                    <inv-form-group label="Ends At"
                                    value="{{ Carbon::parse($event->ends_at)->toDayDateTimeString() }}"
                                    is-disabled></inv-form-group>

                    <inv-event-repeated :value="{{ $event->repeated }}"
                                        :current-type="{{ $event->repeated_type_id  }}"
                                        :types="{{ $repeatedTypes }}" disabled></inv-event-repeated>

                    <div class="flex flex-row justify-between mt-10">
                        <div class="self-center text-sm md:text-lg lg:text-2xl">
                            <i class="fas fa-user-friends"></i>Attendees
                        </div>
                    </div>
                    <hr>
                    <list-group-scrollable>
                        @foreach($attendees as $attendee)
                            <div class="list-group-item border-0">
                                <div class="flex flex-wrap">
                                    <div class="w-full md:w-1/2">
                                        <div class="text-sm font-bold text-grey-darkest md:text-base">
                                            {{ $attendee->user->name }}
                                        </div>
                                        <div class="text-grey-dark text-xs md:text-sm">
                                            {{ $attendee->user->email }}
                                        </div>
                                    </div>
                                    <div class="w-full md:w-1/2">
                                        <inv-attendee-status attendee-type="{{ $attendee->attendeeType->name }}"
                                                             attendee-status="{{ $attendee->attendeeStatus->name }}"></inv-attendee-status>
                                    </div>
                                </div>
                            </div>
                            <hr>
                        @endforeach
                    </list-group-scrollable>

                </div>
            </div>
        </div>
    </div>



@endsection